name: Build and publish HTML

# ci workflow
on: [push]

jobs:
    publish:
        name: Build the Code
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Install Groovy
          run: |
            curl -s get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install groovy
        - name: Build Docs
          run: |
            source "/home/runner/.sdkman/bin/sdkman-init.sh" && ./dtr.sh
        - name: Set Git user
          run: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@4.1.0
          with:
            branch: gh-pages
            folder: target
